<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFrameworks>net48;net6.0</TargetFrameworks>
    <LangVersion>latest</LangVersion>
    <CopyLocalLockFileAssemblies>true</CopyLocalLockFileAssemblies>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Microsoft.Playwright" Version="1.52.0" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\..\HL7Soup\HL7Parser\HL7SoupIntegrations\HL7SoupIntegrations.csproj" />
  </ItemGroup>

  <ItemGroup>
    <None Include="..\DeployCustomLibraries.ps1" Link="DeployCustomLibraries.ps1">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </None>
  </ItemGroup>

  <Target Name="RemoveNet48SatelliteFolders" AfterTargets="CopyFilesToOutputDirectory" Condition="'$(TargetFramework)' == 'net48' and '$(IsCrossTargetingBuild)' != 'true'">
    <ItemGroup>
      <Net48SatelliteDirs Include="$(TargetDir)cs;$(TargetDir)de;$(TargetDir)es;$(TargetDir)fr;$(TargetDir)it;$(TargetDir)ja;$(TargetDir)ko;$(TargetDir)pl;$(TargetDir)pt-BR;$(TargetDir)ru;$(TargetDir)tr;$(TargetDir)zh-Hans;$(TargetDir)zh-Hant" />
    </ItemGroup>
    <RemoveDir Directories="@(Net48SatelliteDirs)" />
  </Target>

</Project>
