<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <TargetFramework>net48</TargetFramework>
    <LangVersion>latest</LangVersion>
    <AssemblyName>EncryptionActivitiesRunner</AssemblyName>
    <RootNamespace>HL7SoupEncryptionActivities.Runner</RootNamespace>
    <CopyLocalLockFileAssemblies>false</CopyLocalLockFileAssemblies>
    <GenerateAssemblyInfo>false</GenerateAssemblyInfo>
  </PropertyGroup>

  <ItemGroup>
    <Compile Include="..\ExtensionRunnerHosting\*.cs" Link="ExtensionRunnerHosting\%(Filename)%(Extension)" />
  </ItemGroup>

  <PropertyGroup><BridgeAdapterSource>$(MSBuildProjectDirectory)/../HL7SoupEncryptionActivities/HL7SoupEncryptionActivities</BridgeAdapterSource></PropertyGroup>
  <Import Project="../ExtensionBridgeRuntime/ExtensionBridgeRuntime.targets" />
</Project>
